=== wackywombaat12/XML-Assignment/Assignment 2/customers.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">

	<xs:element name="customers">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="customer" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="meternumber">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="([0-9])+"/>
										<xs:minLength value="5"/>
										<xs:maxLength value="8"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="name">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first" type="xs:string" />
										<xs:element name="middle" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="last" type="xs:string" />
									</xs:sequence>
									<xs:attribute name="title" type="xs:string" />

								</xs:complexType>
							</xs:element>
							<xs:element name="address">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="street" type="xs:string" />
										<xs:element name="suburb" type="xs:string" />
										<xs:element name="postcode">
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:pattern value="[0-9]{4}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="state">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="NSW|QLD|VIC|NT|ACT|SA|WA|TAS"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="phone">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="number" minOccurs="0" maxOccurs="3">
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:pattern value="[0-9]{10}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="payment" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="reading" type="xs:integer" />
										<xs:element name="amountdue" type="xs:decimal" />
										<xs:element name="paydate" type="xs:string" />
										<xs:element name="paid" type="xs:string" nillable="true"/>
									</xs:sequence>
									<xs:attribute name="date" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="number" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9]"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== wackywombaat12/XML-Assignment/Assignment 2/customers.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

	<customers
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="customers.xsd">
	
		<customer number="BL343456">
			<meternumber>134456</meternumber>
			<name title="">
				<first>Bart</first>
				<middle></middle>
				<last>Simpson</last>
			</name>
			<address>
				<street>45 Olive dr</street>
				<suburb>Sydney</suburb>
				<postcode>2000</postcode>
				<state>NSW</state>
			</address>
			<phone>
				<number>0298576433</number>
				<number>0413335678</number>
				<number>0296784455</number>
			</phone>
			<payment date="29/11/2008">
				<reading>62990</reading>
				<amountdue>0</amountdue>
				<paydate>new ACC</paydate>
				<paid></paid>
			</payment>
			<payment date="28/02/2009">
				<reading>64492</reading>
				<amountdue>242.21</amountdue>
				<paydate>30/03/2009</paydate>
				<paid>242.21</paid>
			</payment>
			<payment date="29/05/2009">
				<reading>65374</reading>
				<amountdue>157.23</amountdue>
				<paydate>24/06/2009</paydate>
				<paid>157.23</paid>
			</payment>
			<payment date="29/08/2009">
				<reading>66348</reading>
				<amountdue>170.60</amountdue>
				<paydate>19/09/2009</paydate>
				<paid>170.60</paid>
			</payment>
		</customer>
		<customer number="TR567903">
			<meternumber>342566</meternumber>
			<name title="">
				<first>Donald</first>
				<middle></middle>
				<last>Duck</last>
			</name>
			<address>
				<street>12 Grey place</street>
				<suburb>Sometown</suburb>
				<postcode>9876</postcode>
				<state>NSW</state>
			</address>
			<phone>
				<number>0432226677</number>
			</phone>
			<payment date="29/08/2009">
				<reading>28132</reading>
				<amountdue>0</amountdue>
				<paydate>new ACC</paydate>
				<paid>0</paid>
			</payment>
		</customer>
		<customer number="VL305888">
			<meternumber>234567</meternumber>
			<name title="Ms">
				<first>Minni</first>
				<middle></middle>
				<last>Mouse</last>
			</name>
			<address>
				<street>368 King St</street>
				<suburb>Cartooncity</suburb>
				<postcode>5678</postcode>
				<state>NSW</state>
			</address>
			<phone>
				<number>0445566543</number>
				<number>0688763344</number>
			</phone>
			<payment date="29/05/2009">
				<reading>998</reading>
				<amountdue>0</amountdue>
				<paydate>new ACC</paydate>
				<paid></paid>
			</payment>
			<payment date="29/08/2009">
				<reading>998</reading>
				<amountdue>34.32</amountdue>
				<paydate>16/09/2009</paydate>
				<paid>34.32</paid>
			</payment>
		</customer>
	</customers>
