=== wackywombaat12/XML-Assignment/Assignment 2/meter_readings.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">

	<xs:element name="meterreadings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="meterreading" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="number">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="([0-9])+"/>
										<xs:minLength value="5"/>
										<xs:maxLength value="8"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="reading" type="xs:positiveInteger" />
						</xs:sequence>
						<xs:attribute name="date" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>

		</xs:complexType>
	</xs:element>

</xs:schema>

=== wackywombaat12/XML-Assignment/Assignment 2/meter_readings.xml
<?xml version="1.0" encoding="ISO-8859-1"?>


<meterreadings 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="meter_readings.xsd">

	<meterreading date="29/11/2009">
		<number>234567</number>
		<reading>1089</reading>
	</meterreading>
	<meterreading date="29/11/2009">
		<number>134456</number>
		<reading>67990</reading>
	</meterreading>
	<meterreading date="29/11/2009">
		<number>342566</number>
		<reading>29011</reading>
	</meterreading>
</meterreadings>
